#SPDX-License-Identifier: MIT-0
galaxy_info:
  author: Renato Alves
  description: OSIRIS for de.NBI
  company: de.NBI
  license: MIT

  min_ansible_version: 2.1

  galaxy_tags:
    - mongodb
    - php
    - httpd
    - osiris
