---
- name: "Ensure restic log dir exists"
  ansible.builtin.file:
    path: "{{ restic_log_dir }}"
    owner: "root"
    group: "root"
    mode: "0750"
    state: "directory"

- name: "Ensure restic log file exists"
  ansible.builtin.file:
    path: "{{ restic_log }}"
    owner: "root"
    group: "root"
    mode: "0700"
    state: "touch"

- name: "Add logrotate configuration for restic backup logs"
  ansible.builtin.template:
    src: "templates/restic.logrotate.j2"
    dest: "/etc/logrotate.d/restic"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "Ensure base backup folder exists"
  ansible.builtin.file:
    path: "{{ backup_restore_base_dir }}"
    owner: "root"
    group: "root"
    mode: "0700"
    state: "directory"

- name: "Delete/Cleanup backup directories"
  include_tasks: delete_backup_dir.yml

- name: "Ensure root bin folder exists"
  ansible.builtin.file:
    path: "{{ cron_bin_dir }}"
    owner: "root"
    group: "root"
    mode: "0700"
    state: "directory"

- name: "Add restic backup and restore script"
  ansible.builtin.template:
    src: "templates/restic_backup_restore.sh.j2"
    dest: "{{ restic_backup_script }}"
    owner: "root"
    group: "root"
    mode: "0700"

- name: "Configure restic for daily backups"
  ansible.builtin.cron:
    name: "OSIRIS backup - Daily at 2:00 (AM)"
    minute: "00"
    hour: "02"
    user: "root"
    job: "{{ cron_bin_dir }}/restic_backup_restore.sh"
    cron_file: ansible_restic_backup_restore
